### PR TITLE
Fix Submitting Little Snitch

### PR DESCRIPTION
**Pull request by IMcPwn**
In the new Little Snitch version your program no longer works. It does not allow you to press 'enter' to submit.

But you CAN still do it via moving the mouse, which I doubt will be changed so I put an optional method for doing such, or even easier you can just use cmd(KEY_ENTER) which I added as the default.

### CODE REVIEW

**Comment by samyk** [comment]
This is awesome, @IMcPwn! Would you mind converting it into an #ifdef/#endif and add a #define at the top so users can simply comment or uncomment a single #define line to enable/disable?

**Comment by IMcPwn** [comment]
No problem, I'm a complete noob so it might take me a few to figure it out but I'll fix it!

P.S I love your work.

**Comment by samyk** [comment]
Thanks!

Here's an example:
http://www.phanderson.com/C/preprocess.html

**Comment by IMcPwn** [comment]
Alright you can take a look. It compiled alright with Arduino, but I don't have time for a full test.

**Comment by IMcPwn** [comment]
Hey Samy, just checking up to see if you got a chance to see my update. Let me know if there's anything else I need to do to it.

**Comment by samyk** [comment]
Thanks @IMcPwn! Merged.

**Pull request merged**
